/*
 * Can_Cfg.h
 *
 *  Created on: Jul 2, 2020
 *      Author: Sahar
 */

#ifndef BSW_COMMUNICATION_INTERFACE_CANIF_CAN_CFG_H_
#define BSW_COMMUNICATION_INTERFACE_CANIF_CAN_CFG_H_





#endif /* BSW_COMMUNICATION_INTERFACE_CANIF_CAN_CFG_H_ */
