/*
 * TransmitECUsUpdate_Cfg.h
 *
 *  Created on: Jul 2, 2020
 *      Author: Sahar
 */

#ifndef BSW_SW_C_TRANSMITECUSUPDATE_SWC_TRANSMITECUSUPDATE_CFG_H_
#define BSW_SW_C_TRANSMITECUSUPDATE_SWC_TRANSMITECUSUPDATE_CFG_H_





#endif /* BSW_SW_C_TRANSMITECUSUPDATE_SWC_TRANSMITECUSUPDATE_CFG_H_ */
